### ISSUE TITLE
Changing pagination format in the URL

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/raft#59] opened 2023-10-04 08:04 UTC
### What problem does this address?

A customer asked how the pagination can be changed in the URL.

With the Raft theme, when pagination is enabled on the blog page, the next page generates the following URL

`blog/?query-4-page=2`

while with the Twenty Twenty-Three theme the URL is

`blog/page/2/`

I tried changing the permalinks and I don't get the same format as in Twenty Twenty-Three.

### What is your proposed solution?

Format the pagination url as **page/_page_number_/** instead of **query-4-page=_page_number_**

Requested here: https://secure.helpscout.net/conversation/2361470032/385548/

### Will this feature require documentation? (Optional)

No.

**Comment by HardeepAsrani** [comment] 2023-10-26 01:45
@JohnPixle This should also be fixed by this: https://github.com/Codeinwp/raft/commit/e9ea99fc05f6f290ff06ae37575b2315ffd0acb2 as it was being caused by this https://github.com/Codeinwp/raft/issues/58

**Closed** 2023-12-18 14:58 UTC
Labels: new feature, customer report
