### ISSUE TITLE
Update the demo site

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/raft#37] opened 2023-03-24 19:59 UTC
### Description

The current demo site looks bad on mobile for e.g ( the header) and can use more elements + a way to switch between styles.

Can we do a proper demo for this? As I was thinking to promote it with the 6.2 release, this would be helpful.

### Step-by-step reproduction instructions

Go to : https://demosites.io/raft/

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment] 2023-03-26 01:48
@mghenciu can you help here with what more you think we can do to improve the design that works great on all screens?

**Comment by selul** [comment] 2023-03-26 09:09
@ineagu, from my point of view the current demo is looking quite good for promotion and marketing; I don't see those as blockers in case they take too much to not promote it. Do you think otherwise?

**Comment by ineagu** [comment] 2023-03-26 09:16
As I’ve mentioned is broken on mobile ( the heading take the whole screen), the default w.org preview looks better.We dont need anything fancy, just replicate the w.org oneSent from my iPhoneOn Mar 26, 2023, at 11:09, Marius Cristea ***@***.***> wrote:﻿
@ineagu, from my point of view the current demo is looking quite good for promotion and marketing; I don't see those as blockers in case they take too much to not promote it. Do you think otherwise?

**Comment by selul** [comment] 2023-03-26 09:18
For me seems good as it looks https://vertis.d.pr/i/as5rAo

**Comment by selul** [comment] 2023-03-26 09:18
Can you share your browser when you get some time https://www.whatsmybrowser.org/

**Comment by ineagu** [comment] 2023-03-26 09:21
Here is on Safari, iphone for e.gSent from my iPhoneOn Mar 26, 2023, at 11:18, Marius Cristea ***@***.***> wrote:﻿
Can you share your browser when you get some time https://www.whatsmybrowser.org/

**Comment by selul** [comment] 2023-03-26 09:23
Sure, no need to rush; you can share the details whenever you get some time.

**Comment by ineagu** [comment] 2023-03-26 09:24
![9586CE89-A134-4B7F-9795-45C48A3A3794](https://user-images.githubusercontent.com/1849868/227766676-52f52789-60f2-4256-a8e4-d3d70fd5aecb.png)


Here is the screen on Safari, iphone, didn’t work in the last message.

**Comment by ineagu** [comment] 2023-03-26 09:26
And wordpress.org 
![DA376399-FF07-44FF-8035-1E35A510CCA7](https://user-images.githubusercontent.com/1849868/227766769-d53eb04e-c530-45e9-a982-8aeea0ffb2a7.png)

**Comment by ineagu** [comment] 2023-03-26 09:27
Here is the browser link https://www.whatsmybrowser.org/b/NVVC8

**Comment by mghenciu** [comment] 2023-03-26 10:59
Should look better now:
![image](https://user-images.githubusercontent.com/52494172/227771212-3f864e6e-9ee5-48a4-95f3-bf0aace5b754.png)


The issue was caused by a Custom font value (72px) for the Main heading on the Homepage.
At this stage, is not possible to have different font size on Desktop and Mobile in FSE. The only way to do this is with Code, by defining responsive font size values.

**Comment by HardeepAsrani** [comment] 2023-04-21 11:20
Closing this as Mihai confirmed this was fixed, and creating a new issue for another issue that we found.

**Closed by HardeepAsrani** 2023-04-21 11:20 UTC
Labels: bug
